FROM        alpine:<%= ENV.fetch 'ALPINE_VERSION' %>

ENV         TAG=<%= ENV.fetch 'TAG' %> \
            RABBITMQ_VERSION=<%= ENV.fetch 'RABBITMQ_VERSION' %> \
            RABBITMQ_MNESIA_BASE=/var/db/rabbitmq \
            DATA_DIRECTORY=/var/db \
            RABBITMQ_LOGS=- \
            RABBITMQ_SASL_LOGS=-
ENV         RABBITMQ_HOME=/srv/rabbitmq_server-${RABBITMQ_VERSION} \
            PLUGINS_DIR=/srv/rabbitmq_server-${RABBITMQ_VERSION}/plugins \
            RABBITMQ_ENABLED_PLUGINS_FILE=${DATA_DIRECTORY}/enabled_plugins
ENV         PATH=$RABBITMQ_HOME/sbin:$PATH

RUN         mkdir -p /srv && \
            cd /srv && \
            ARCHIVE="rabbitmq.tar.<%= ENV.fetch 'ARCHIVE_FORMAT' %>" && \
            apk add --no-cache --update curl tar gzip bash openssl pwgen && \
            curl \
              -fsSL "<%= ENV.fetch 'RABBITMQ_DOWNLOAD_URL' %>" \
              -o "${ARCHIVE}" && \
            echo "<%= ENV.fetch 'RABBITMQ_SHA1SUM' %>  ${ARCHIVE}" | sha1sum -c - && \
            apk add --no-cache --update erlang erlang-mnesia erlang-public-key erlang-crypto erlang-ssl \
                        erlang-sasl erlang-asn1 erlang-inets erlang-os-mon erlang-xmerl erlang-eldap xz bash && \
            tar -xvf "$ARCHIVE" && \
            rm -f "${ARCHIVE}" && \
            mkdir "${DATA_DIRECTORY}" && \
            "${RABBITMQ_HOME}/sbin/rabbitmq-plugins" enable --offline rabbitmq_management && \
            "${RABBITMQ_HOME}/sbin/rabbitmq-plugins" enable --offline rabbitmq_shovel && \
            "${RABBITMQ_HOME}/sbin/rabbitmq-plugins" enable --offline rabbitmq_shovel_management && \
            cp ${RABBITMQ_ENABLED_PLUGINS_FILE} /tmp/enabled_plugins_template && \
            apk del --purge tar gzip

COPY        etc/openssl.cnf /ssl/testca/openssl.cnf
COPY        etc/rabbitmq.config.template /etc/rabbitmq.config.template
COPY        etc/rabbitmqadmin.conf /usr/local/bin/rabbitmqadmin.conf
COPY        bin/run-database.sh /usr/bin/wrapper
COPY        bin/initialize-certs.sh /usr/bin/initialize-certs
COPY        "${TAG}"/bin/rabbitmqadmin /usr/local/bin/rabbitmqadmin

RUN         VERSION="<%= ENV.fetch 'DELAYED_MESSAGE_EXCHANGE_VERSION' %>" \
         && PLUGINS="<%= ENV.fetch 'RABBITMQ_PLUGINS' %>" \
         && DOWNLOAD="rabbitmq_delayed_message_exchange-${VERSION}" \
         && curl -fsSL "<%= ENV.fetch 'DELAYED_MESSAGE_PLUGIN_DOWNLOAD' %>" -o "$DOWNLOAD" \
         && echo "<%= ENV.fetch 'DELAYED_MESSAGE_EXCHANGE_SHA1SUM' %>  ${DOWNLOAD}" | sha1sum -c - \
         && (unzip "${DOWNLOAD}" || mv "${DOWNLOAD}" "${DOWNLOAD}.ez") \
         && mv "${DOWNLOAD}.ez" "/srv/rabbitmq_server-${RABBITMQ_VERSION}/plugins/" \
         && rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange

RUN         ln -s /var/db/testca/cacert.pem /ssl/cacert.pem && \
            ln -s /var/db/server/cert.pem /ssl/cert.pem && \
            ln -s /var/db/server/key.pem /ssl/key.pem

ADD         bin/install-bats.sh /usr/bin/install-bats
ADD         test /tmp/test

EXPOSE      5671 15671
VOLUME      ["$DATA_DIRECTORY"]
ENTRYPOINT  ["/usr/bin/wrapper"]
